### ISSUE TITLE
Something wrong with console_richlog.py

### ISSUE THREAD

**Issue by belonesox** [davidfokkema/playground-textual#1]
Hello! Great examples!

But, looks something wrong with `console_richlog.py`...
(`textual==0.44.1`) 

![image](https://github.com/davidfokkema/playground-textual/assets/1609739/67eed10e-89bd-40fa-89aa-573cc1ca8e61)

Is it bug or something wrong in my setup?

**Comment by davidfokkema** [comment]
Thanks! I do have to separate these scripts into 'working examples' and 'showcasing an issue'. This script was trying to fix the problem that a console script might show some nice updating progress bars while a log would fill up with hundreds of lines of progress bars slowly building up to completion. In fact, when you run `python -m rich.progress | less` then Rich won't even show the progress bars to make sure it doesn't spam log files. I've now updated the script to bring it back in working condition, but still showing the problem of many many many lines of output.

**Comment by davidfokkema** [comment]
Fixed in 380854d5e39c7d21ce3f8b8ec40e83435e662671

**Comment by belonesox** [comment]
Thank you very much! May be you know answer to this question https://github.com/Textualize/textual/discussions/3888 ?

**Comment by davidfokkema** [comment]
> Thank you very much! May be you know answer to this question [Textualize/textual#3888](https://github.com/Textualize/textual/discussions/3888) ?

Answered in that issue!
